package com.clinic.clinicapi.entity;

// Predefined list of valid doctor specialties
public enum Specialty {

    GENERAL_MEDICINE,
    CARDIOLOGY,
    DERMATOLOGY,
    PEDIATRICS,
    ORTHOPEDICS,
    NEUROLOGY,
    DENTISTRY,
    TESTING,

    INTERNAL_MEDICINE,
    FAMILY_MEDICINE,
    EMERGENCY_MEDICINE,
    ENDOCRINOLOGY,
    GASTROENTEROLOGY,
    HEMATOLOGY,
    ONCOLOGY,
    RHEUMATOLOGY,
    PULMONOLOGY,
    NEPHROLOGY,
    UROLOGY,
    OPHTHALMOLOGY,
    ENT,
    PSYCHIATRY,
    RADIOLOGY,
    ANESTHESIOLOGY,
    GENERAL_SURGERY,
    PLASTIC_SURGERY,
    OBSTETRICS_GYNECOLOGY,
    INFECTIOUS_DISEASE,
    ALLERGY_IMMUNOLOGY,
    PATHOLOGY,
    PHYSIOTHERAPY,
    NUTRITION,
    SPORTS_MEDICINE
}